<div class="row">
    <div class="col-md-12">
        <h1>Lista notatek tagu <strong><?= $this->tag->getName() ?></strong></h1>
    </div>
</div>
<div class="row margin-top-20">
    <div class="col-md-12">
        <?php if($this->tag->getNotes()): ?>
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th style="width: 60px;">ID</th>
                        <th>Nazwa</th>
                        <th style="width: 80px;">Akcje</th>
                    </tr>
                </thead>
                <tbody>
                <?php foreach($this->tag->getNotes() as $note): ?>
                    <tr>
                        <td style="width: 60px;"><?= $note->getId() ?></td>
                        <td><?= $note->getTitle() ?></td>
                        <td>
                            <a href="<?= $this->url('note', ['action' => 'edit', 'id' => $note->getId()]) ?>" class="btn btn-success btn-xs" title="Edytuj">
                                <span class="glyphicon glyphicon-edit"></span>
                            </a>
                            <a href="<?= $this->url('note', ['action' => 'delete', 'id' => $note->getId()]) ?>" class="btn btn-danger btn-xs" title="Usuń">
                                <span class="glyphicon glyphicon-trash"></span>
                            </a>
                        </td>
                    </tr>
                <?php endforeach; ?>
                </tbody>
            </table>
        <?php else: ?>
            <div class="alert alert-warning" role="alert">Lista tagów jest pusta.</div>
        <?php endif; ?>
    </div>
</div>
