<?php foreach($this->flashMessenger()->getSuccessMessages() as $message): ?>
    <div class="alert alert-success alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
        <?= $this->translate($message) ?>
    </div>
<?php endforeach; ?>

<?php foreach($this->flashMessenger()->getErrorMessages() as $message): ?>
    <div class="alert alert-danger alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
        <?= $this->translate($message) ?>
    </div>
<?php endforeach; ?>

<?php foreach($this->flashMessenger()->getInfoMessages() as $message): ?>
    <div class="alert alert-info alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
        <?= $this->translate($message) ?>
    </div>
<?php endforeach; ?>

<?php foreach($this->flashMessenger()->getWarningMessages() as $message): ?>
    <div class="alert alert-warning alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
        <?= $this->translate($message) ?>
    </div>
<?php endforeach; ?>
