<h1>Formularz dodawania kategorii</h1>

<?php $this->form->prepare(); ?>
<div class="row margin-top-20">
    <?= $this->form()->openTag($this->form); ?>
        <div class="col-md-6">
            <div class="form-group">
                <?= $this->formLabel($this->form->get('name')) ?>
                <?= $this->formElement($this->form->get('name')) ?>
                <?= $this->formElementErrors($this->form->get('name')) ?>
            </div>
        </div>

        <div class="col-md-6">
            <div class="form-group">
                <?= $this->formLabel($this->form->get('icon')) ?>
                <?= $this->formElement($this->form->get('icon')) ?>
                <?= $this->formElementErrors($this->form->get('icon')) ?>
            </div>
        </div>

        <div class="col-md-8 col-md-offset-2 text-right">
            <?= $this->formSubmit($this->form->get('submit')) ?>
        </div>
    <?= $this->form()->closeTag(); ?>
</div>