<div class="row margin-top-30">
    <div class="col-md-12">
        <table class="table table-striped">
            <thead>
            <tr>
                <th style="width: 30%;">Data</th>
                <th>Treść</th>
            </tr>
            </thead>
            <tbody>
            <?php foreach($this->logs as $log): ?>
                <tr>
                    <td><?= $log->getDate()->format('Y-m-d H:i:s') ?></td>
                    <td><?= $log->getContent() ?></td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
    </div>
</div>
