<?php
use Zend\Mvc\Application;
?>
<div class="content">
    <h1>Zasób nie został odnaleziony
        <small>(404)</small>
    </h1>
    <p class="lead">
        <?= $this->translate($this->message) ?>
    </p>
    <?php if (! empty($this->reason)) :
        switch ($this->reason) {
            case Application::ERROR_CONTROLLER_CANNOT_DISPATCH:
                $reasonMessage = 'The requested controller was unable to dispatch the request';
                break;
            case Application::ERROR_MIDDLEWARE_CANNOT_DISPATCH:
                $reasonMessage = 'The requested middleware was unable to dispatch the request';
                break;
            case Application::ERROR_CONTROLLER_NOT_FOUND:
                $reasonMessage = 'The requested controller could not be mapped to an existing controller class';
                break;
            case Application::ERROR_CONTROLLER_INVALID:
                $reasonMessage = 'The requested controller was not dispatchable';
                break;
            case Application::ERROR_ROUTER_NO_MATCH:
                $reasonMessage = 'The requested URL could not be matched by routing';
                break;
            default:
                $reasonMessage = 'We cannot determine at this time why a 404 was generated';
                break;
        }
        ?>
        <p><?= $this->translate($reasonMessage) ?></p>
    <?php endif ?>
    <a class="btn btn-blk" href="<?= $this->url('home') ?>">Powród na stronę główną</a>
</div>