<!DOCTYPE html>
<html>
<head>
    <?= $this->headTitle('Digital Code Repository')->setSeparator(' - ')->setAutoEscape(false) ?>

    <?= $this->headMeta()
        ->appendName('charset', 'UTF-8')
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>

    <?= $this->headLink(
        ['rel' => 'shortcut icon',
            'type' => 'image/vnd.microsoft.icon',
            'href' => $this->basePath() . '/favicon.ico'
        ]
    )
        ->prependStylesheet($this->basePath('css/login.css'))
        ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
    ?>
</head>
<body>
<div class="login-container">
    <h1>Logowanie</h1><br>
    <?php $this->form->prepare(); ?>
    <?= $this->form()->openTag($this->form); ?>
    <?= $this->formElement($this->form->get('email')) ?>
    <?= $this->formElementErrors($this->form->get('email')) ?>

    <?= $this->formElement($this->form->get('password')) ?>
    <?= $this->formElementErrors($this->form->get('password')) ?>

    <?= $this->formSubmit($this->form->get('submit')) ?>
    <?= $this->form()->closeTag(); ?>

    <div class="login-help">
        <a href="<?= $this->url('remember') ?>">Zapomniałem hasła</a>
    </div>
</div>
</body>
</html>

