<?php $this->headLink()->prependStylesheet($this->basePath('css/timeline.css')); ?>

<header class="page-header text-center">
    <h1>Linia czasu</h1>
    <div class="row margin-top-30 js-tags">
        <?php foreach($this->tags as $tag) : ?>
            <a class="btn btn-blk margin-left-10" href="#" data-id="<?= $tag->getId() ?>"><?= $tag->getName() ?></a>
        <?php endforeach; ?>
    </div>
</header>

<ul id="timeline" class="timeline">
<!--    <li><div class="tldate">Apr 2014</div></li>-->
</ul>

<?php $this->inlineScript()->prependFile($this->basePath('js/infinity_scroll.js')) ?>
