<?php $this->headLink()->prependStylesheet($this->basePath('css/timeline.css')); ?>

<header class="page-header text-center">
    <h1>Linia czasu</h1>
    <div class="row margin-top-30">
        <a class="btn btn-blk margin-left-10" href="#">Przykładowy tag</a>
        <a class="btn btn-blk margin-left-10" href="#">Przykładowy tag</a>
        <a class="btn btn-blk margin-left-10" href="#">Przykładowy tag</a>
        <a class="btn btn-blk margin-left-10" disabled="disabled" href="#">Przykładowy tag</a>
        <a class="btn btn-blk margin-left-10" disabled="disabled" href="#">Przykładowy tag</a>
    </div>
</header>

<ul id="timeline" class="timeline">
    <li><div class="tldate">Apr 2014</div></li>
</ul>

<script>
    DATA = <?= $this->data ?>;
</script>
<?php $this->inlineScript()->prependFile($this->basePath('js/infinity_scroll.js')) ?>
